<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>NRules.Samples.ClaimsExpert.Service</AssemblyName>
    <RootNamespace>NRules.Samples.ClaimsExpert.Service</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" />
    <PackageReference Include="NRules" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="System.Data.SQLite.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClaimsExpert.Contract\ClaimsExpert.Contract.csproj" />
    <ProjectReference Include="..\ClaimsExpert.Domain\ClaimsExpert.Domain.csproj" />
    <ProjectReference Include="..\ClaimsExpert.Rules\ClaimsExpert.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
